FROM tomcat:8.0-jre8

ARG AUTH_SITES_FILE_NAME
ARG HTTP_PORT
ARG HTTPS_PORT
ARG HOST_NAME
ARG METADATA_CONFIG

# TODO: remove after file gets completed
RUN apt update && apt install -y less vim

ENV WEB_APP_PATH=/opt/security-manager
ENV WEB_APP_CONF_PATH=/opt/security-manager-conf

COPY ./secmgr/target/security-manager-1.0-SNAPSHOT ${WEB_APP_PATH}
COPY ./config ${WEB_APP_CONF_PATH}

RUN cd ${WEB_APP_CONF_PATH} && ln -s ${AUTH_SITES_FILE_NAME} SampleAuthSites.json

COPY ./config/logging.properties ${WEB_APP_PATH}/WEB-INF/classes
COPY ./config/security-manager.xml ${CATALINA_HOME}/conf/Catalina/localhost/
RUN sed -i "s@#APP_PATH#@${WEB_APP_PATH}@" ${CATALINA_HOME}/conf/Catalina/localhost/security-manager.xml \
	&& sed -i "s@#AUTHN_SITES_PATH#@${WEB_APP_CONF_PATH}/SampleAuthSites.json@" ${CATALINA_HOME}/conf/Catalina/localhost/security-manager.xml \
	&& sed -i "s@#CONFIG_DIR#@${WEB_APP_CONF_PATH}@" ${WEB_APP_CONF_PATH}/SampleAuthSites.json

RUN cp --backup=numbered ${WEB_APP_CONF_PATH}/server.xml ${CATALINA_HOME}/conf

# RUN keytool -genkey -noprompt -trustcacerts -keyalg RSA -alias tomcat -dname "CN=${HOST_NAME}, OU=ou, O=o, L=l, S=s ,C=us" -keystore ${WEB_APP_CONF_PATH}/keystore.p12 -keypass changeit -storepass changeit -storetype PKCS12
COPY ./keystore.p12 ${WEB_APP_CONF_PATH}

COPY ./secmgr1.crt /usr/local/share/ca-certificates/secmgr1.crt
RUN update-ca-certificates
RUN keytool -noprompt -import -alias secmgr1 -file /usr/local/share/ca-certificates/secmgr1.crt -keystore cacerts -storepass changeit


RUN sed -i -e "s|{HTTP_PORT}|${HTTP_PORT}|" -e "s|{HTTPS_PORT}|${HTTPS_PORT}|" ${CATALINA_HOME}/conf/server.xml

RUN cp ${WEB_APP_CONF_PATH}/${METADATA_CONFIG} ${WEB_APP_CONF_PATH}/saml-metadata.xml

EXPOSE ${HTTPS_PORT}
EXPOSE ${HTTP_PORT}



